### ISSUE TITLE
Update to use hazelcast 5.1

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-sessions#138]
Need fix the following:
- clone from the `gkwan-ibm-hazelcast-51` branch
- update the `src/main/liberty/config/hazelcast-config.xml` as https://github.com/OpenLiberty/open-liberty/issues/20467#issuecomment-1072884158
- update the server.xml as 
```
    <httpSessionCache libraryRef="jCacheVendorLib"
        hazelcast.jcache.provider.type="member"
        hazelcast.config.location="file:${server.config.dir}/hazelcast-config
    />
```
- update Dockerfile
  - comment out `RUN configure.sh`
- update README.adoc
  - at the beginning of the **Running the application** section, download hazelcast 5.1 from https://hazelcast.com/open-source-projects/downloads/ and run it local 
  - at the end of **Starting and preparing your cluster for deployment** section, ask user to install Hazelcast operator to kubernetes by https://docs.hazelcast.com/operator/latest/get-started 
- fix the automation test `test.sh`

**Comment by irobins** [comment]
@gkwan-ibm ... I could use the guide with less changes:  embedded mode still works for Hazelcast 5.1. 
When I locally updated the pom.xml for the OL JCache and Hazelcast guide (https://openliberty.io/guides/sessions.html) to uplevel the embedded Hazelcast to 5.1, the specific minimal changes I needed to get up to and including "Running the application" were:
When I locally updated the pom.xml for the OL JCache and Hazelcast guide (https://openliberty.io/guides/sessions.html) to uplevel the embedded Hazelcast to 5.1, the specific **minimal** changes I needed to get past the problem @gkwan-ibm describes above were:
1) use the `hazelcast.config.location` property rather than the URI attribute of `<httpSessionCache>` in the server.xml: 
```
<httpSessionCache libraryRef="jCacheVendorLib">
    <properties hazelcast.config.location="file:${server.config.dir}/hazelcast-config.xml"/>
</httpSessionCache>`
```

This was required to locate the hazelcast-config.xml at all. 
2) Since Hazelcast 4, the default Hazelcast JCache provider is the client-side CachingProvider. (https://docs.hazelcast.com/imdg/4.1/migration-guides#jcache-default-caching-provider ) Since this OL guide is designed to use Hazelcast embedded in the application instances, the default now has to be overridden to the member-side provider implementation using the `hazelcast.jcache.provider.type` property. As @joshfuson mentions above, its too late in the Hazelcast initialization to define this as a property through the `<httpSessionCache>` element in server.xml so it can be set in the Liberty bootstrap.poperties:
```hazelcast.jcache.provider.type = member```
3) Since Hazelcast 4 the hazelcast config `<group>` element is replaced by the `<cluster-name>` element (https://docs.hazelcast.com/imdg/4.1/migration-guides#changes-in-security-configurations). So for the application in this guide the hazelcast-config.xml needs to be changed to:

```
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-5.1.xsd">

    <!--
        The name of the cluster. All members of a single cluster must have the same cluster name
        configured and a client connecting to this cluster must use it as well.
    -->
    <cluster-name>CartCluster</cluster-name>

</hazelcast>
```


That was sufficient. I did not need to download hazelcast 5.1 and run it local

**Comment by irobins** [comment]
Actually, while my (1) above works for both client (default) and hazelcast.jcache.provider.type = member, the the alternative use of the uri attribute continues to work for server/member-side provider type but not for client (default) provider type.

**Comment by gkwan-ibm** [comment]
I have no luck for https://github.com/OpenLiberty/guide-sessions/issues/138#issuecomment-1102756816. will continue to try out
